### PR TITLE
Let Rate do the trivial interest manipulations

### PR DESCRIPTION
**Pull request by kasperrisager**
The trivial interest manipulations are moved from depending on Constant to depending on Rate

### CODE REVIEW

**Comment by kasperrisager** [comment]
Purpose is to move the responsibility for trivial interest accumulation to depend on `Rate`. Before this PR it went through `Constant<:AbstractYield`, but this makes it difficult to untangle simple rates from yield curves. With this inverted dependency, rate logic can be separated from yield curve logic.

**Comment by alecloudenback** [comment]
Is this still a draft/WIP?

**Comment by kasperrisager** [comment]
Wanted to know if there was appetite for going in this direction before finishing up a proper pr.

**Comment by alecloudenback** [comment]
I'm not opposed to it - it seems like there's a degree of API consistency of technically `discount` is only defined on `AbstractYield`s and`Rate`s are used to construct yield curves. 

However, I do see how folks would want to use discounting on rates (thus the promotion to `Constant` yield curve. 

From a performance standpoint, Julia might inline the promotion and so there may or may not be a performance benefit from skipping `Constant`

**Comment by kasperrisager** [comment]
Superseded by #80.

**Pull request closed without merging**
